# Generated by Django 4.0.5 on 2022-06-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date_privacy',
            field=models.CharField(choices=[('PR', 'Private'), ('PA', 'Public'), ('PY', 'Public (Year Only)'), ('PM', 'Public (Year and Month Only)')], default='P', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='links',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
