# Generated by Django 4.0.5 on 2022-06-10 14:37

from django.db import migrations, models
import utils.validators


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_date',
            field=models.DateField(validators=[utils.validators.validate_age]),
        ),
    ]
