# Generated by Django 4.0.5 on 2022-06-07 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_gender_alter_profile_birth_date_privacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Non-Binary'), ('P', 'Not Specified')], default='P', max_length=1),
        ),
    ]
