# Generated by Django 4.0.5 on 2022-06-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_profile_avatar_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='avatar_url',
            new_name='avatar',
        ),
    ]
