# Generated by Django 4.0.5 on 2022-06-18 16:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 18, 16, 55, 14, 712067)),
        ),
    ]
