# Generated by Django 4.0.5 on 2022-06-18 16:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_last_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_online',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
